name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug.
        Please fill out the sections below so we can reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the application is affected?
      options:
        - Gene Search
        - Variant Fetching & Filtering
        - Carrier Frequency Calculation
        - Clinical Text Generation
        - Template / Language Settings
        - UI / Layout / Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Describe what went wrong.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Search for gene "CFTR"
        2. Select gnomAD v4.1
        3. Click "Fetch Variants"
        4. See error in ...
    validations:
      required: true

  - type: dropdown
    id: gnomad-version
    attributes:
      label: gnomAD Version
      description: Which gnomAD dataset version were you using?
      options:
        - gnomAD v4.1 (GRCh38)
        - gnomAD v3.1.2 (GRCh38)
        - gnomAD v2.1.1 (GRCh37)
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) does this occur in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console output
      description: Open DevTools (F12 > Console) and paste any errors. This is automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues to avoid duplicates
          required: true
