name: Documentation Improvement
description: Suggest improvements to documentation or help content
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Documentation area
      description: What part of the documentation needs work?
      options:
        - In-app help / FAQ
        - Methodology description
        - README / setup instructions
        - Clinical text templates
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What needs to be improved?
      description: Describe what is missing, unclear, or incorrect.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested change
      description: If you have a specific improvement in mind, describe it here.
    validations:
      required: false
